// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdbrK2GMJ3aIxuoJjSg2VWtvVy0tDLVDU',
    appId: '1:48801867552:web:e80f4635ee0769cbff1945',
    messagingSenderId: '48801867552',
    projectId: 'tekberd4makeawish',
    authDomain: 'tekberd4makeawish.firebaseapp.com',
    storageBucket: 'tekberd4makeawish.firebasestorage.app',
    measurementId: 'G-N2Y85KJ9TV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiD0e3XsgQ9LZwDu-pTpzFgUYrwTA9lDk',
    appId: '1:48801867552:android:636586223d9635d5ff1945',
    messagingSenderId: '48801867552',
    projectId: 'tekberd4makeawish',
    storageBucket: 'tekberd4makeawish.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1qd3PpKVgG1_heneZaf9tpeWcxMQBC5s',
    appId: '1:48801867552:ios:4a7abe724fdc2f04ff1945',
    messagingSenderId: '48801867552',
    projectId: 'tekberd4makeawish',
    storageBucket: 'tekberd4makeawish.firebasestorage.app',
    iosBundleId: 'com.example.finalproject2',
  );
}
